[network]
peer_key_file = "temp-state/dev/1/peer_key.dat"
listen_addresses = [
	"/ip4/127.0.0.1/tcp/9101/ws",
]
seed_nodes = [
	{ address = "/ip4/127.0.0.1/tcp/9100/ws" }
]

[consensus]
network = "dev-albatross"
min_peers = 0

[database]
path = "temp-state/dev/1"

[log]
level = "trace"
timestamps = true

[log.tags]
libp2p_swarm = "debug"
lock_api = "trace"

[validator]
validator_address = "NQ39 K237 MLYG V8YJ 37MM 4DX8 4C17 X58C PR5P"
signing_key_file = "temp-state/dev/1/signing_key.dat"
signing_key = "6706c8f2d032aab7c4f2375afc48aabfaba3ae0af494d57e844a5eab25b8f2ba"
voting_key_file = "temp-state/dev/1/voting_key.dat"
voting_key = "4a437f4badf338b974b6d7cab9b16ac697b6d8bb081b4ce91044f640652f8f3387c18b774c708218bd8e8842154b0d35768179b0b0192489b9133aea8d9bfddbaba756fa018fc3844b6145d8ae9c7429ca0bd525dd24fa2b2c40bdeb118a0100"
fee_key_file = "temp-state/dev/1/fee_key.dat"
fee_key = "2090e0b66563ac5cf1456e5cffd3a8956533ccb9d7891e9550a8a01635b5d4b9"
